### ISSUE TITLE
HasValue instance for CommandFields

### ISSUE THREAD

**Issue by matthewleon** [pcapriotti/optparse-applicative#120]
Shouldn't we be able to specify a default command?

**Comment by d12frosted** [comment]
Probably you are right. But as temporary workaround you can use `(subparser ... ) <|> (pure defaultValue)`.

**Comment by HuwCampbell** [comment]
This issue is a bit old. I think this is a won't fix for three reasons:

1. one benefit of `HasValue` is that it combines well with `showDefault`, which `subparser` can't use. 

2. defaults for sub-commands doesn't seem like good practice. I can't think of a non-contrived program which does this.

3. the workaround shown above is trivially simple

**Comment by HuwCampbell** [comment]
Thanks for the issue :)
