### ISSUE TITLE
Invalid options and invalid arguments after parser has succeeded not displaying

### ISSUE THREAD

**Issue by drwebb** [pcapriotti/optparse-applicative#164]
You can reproduce these examples using `Examples.Commands`.

`exampleMain --foo hello` shows "Invalid argument --foo". If instead the invalid argument is after the command the usage is shown without displaying the invalid argument.

Trying to track down the error lead me to this line:
https://github.com/pcapriotti/optparse-applicative/blob/8083ed608cef3e75c5d80872d26afea47c42096c/Options/Applicative/Common.hs#L219

Removing the first case in the alternative corrects the behavior, but I'm not sure what else doing this might break (possibly something with backtracking?). It does seem like a strange place to fail with a `MissingError`, because there are still more arguments to parse.

**Comment by HuwCampbell** [comment]
Thanks for the report. Yep, this isn't ideal.

FYI: the hoist is there so we can complete subcommand parsers and then drop back into the parent parser (which could require more stuff). That `MissingError` never gets shown, it's just to make the types like up.

In your example, both parsers (hello and the root parser) have completed correctly, and the error has occurred on the guard in `runParserFully`. So instead of the guard I need to be explicitly that state that there's left over items which weren't parsed.

**Comment by HuwCampbell** [comment]
PR up.

**Comment by HuwCampbell** [comment]
I believe this is fixed.

**Comment by drwebb** [comment]
Great, can confirm the issue seems to be fixed.
