### ISSUE TITLE
Trying to supply an optional parameter with a default value in optparse-applicative

### ISSUE THREAD

**Issue by lucamolteni** [pcapriotti/optparse-applicative#194]
We're trying to implement this three conditions logic:

- If the user supplies the option with a value, that value gets used
- If the user doesn't supply the option, use a default value
- If the user supply the option without a value, use a different default value

But we cannot understand how to do it currently in optparse-applicative.

We tried using 

```
     <$> strOption
         ( long "option-name"
         <> value "defaultValue"
         <> showDefault
        <> metavar "TARGET"
        <> help "Target for the greeting" )
```

But this maps only the first two cases.

**Comment by HuwCampbell** [comment]
I believe that what you're trying to do could lead to an ambiguous parse, which is why we don't support optional values for options.

For example, if I supported and had an optional value option `--foo` and a flag  `--bar`, is `--foo --bar` the option with value `--bar`, or the default value with the flag switched on? What if instead of a switch we had many positional string arguments, is the first string the option's value or the first positional?

I would suggest using the alternative instance of `Parser` – having a `flag'`, an `option`, and a `pure` value for the default (you'll need different names for the flag and option of course).

**Comment by HuwCampbell** [comment]
Comments? or can I close this?

**Comment by lucamolteni** [comment]
No thanks, the workaround seems clear.
