### ISSUE TITLE
Nested usage info for dependent options?

### ISSUE THREAD

**Issue by sjakobi** [pcapriotti/optparse-applicative#220]
Take an option structure like this:

```
data Opts = Opts
  { a :: String
  , b :: Maybe B
  }

optsParser :: Parser Opts
optsParser = Opts
  <$> strOption (long "a")
  <*> optional bParser

data B = B
  { b0 :: String
  , b1 :: Maybe String
  }

bParser :: Parser B
bParser = B
  <$> strOption (long "b0")
  <*> optional (strOption (long "b1"))

main :: IO ()
main =
  void $ execParser
    (info (helper <*> optsParser) fullDesc)
```

The resulting usage info is

```
Usage: dependent-opts-exe --a ARG [--b0 ARG] [--b1 ARG]
```

This usage info doesn't reveal that `--b1` can only be passed in if `--b0` is given. Therefore I would prefer to see 

```
Usage: dependent-opts-exe --a ARG [--b0 ARG [--b1 ARG]]
```

Is this something that `optparse-applicative` could do?

**Comment by HuwCampbell** [comment]
Whoops

**Comment by HuwCampbell** [comment]
I don't think there's a fundamental reason that this couldn't be implemented.

It would probably require changing the `OptTree` structure we generate in `treeMapParser` to hold the default (and multi) information, instead of passing it to the existential `Option` render function.

Will look into it.

**Comment by HuwCampbell** [comment]
Fixed in master
