### ISSUE TITLE
`many` broke in GHC 8.0

### ISSUE THREAD

**Issue by pietervdvn** [pcapriotti/optparse-applicative#239]
In my program, no, one or more example files can be included.

However, using many never yields a result since the switch to ghc 8.0 (with the new Base-package). In ghc 7.10, this did however work.

```
data Args = Args 	{ tsFile		:: String
			, exampleFiles		:: ExampleFile
			} deriving (Show)


data ExampleFile	= ExFileArgs
	{ fileName	:: String
	, parser	:: Name
	, lineByLine	:: Bool
	, symbol	:: Maybe Symbol
	, function	:: Maybe Name
	, stepByStep	:: Maybe Name
	} deriving (Show)

args	:: Parser Args
args	= Args <$> argument str
			(metavar "TYPESYSTEM-FILE"
			<> help "FilePath of the typesystem-file"
			<> action "file")
		<*> many targetFile

```

`./Main.exe file.typesystem examples.txt -l` gives the help text since GHC 8.0

**Comment by HuwCampbell** [comment]
We a good few tests using `many` in the test suite, which runs with 8.0.1, (as well as all the way back to 7.0.4). So unless it broke with 8.0.2, I think is unlikely to be that.

As of 0.13.0 however, I made the run functions for `many` and `some` "lazier" so that they work for parsers with more than one element, see #191 . I think you're probably hitting something to do with this change.

What version of optparse are you using; what's your definition of `targetFile`; and what's the precise version of GHC (just in case)?

**Comment by pietervdvn** [comment]
GHCI 8.0.1
optparse-applicative-0.12.1.0 (the one that comes with stack)

Turns out my previous build (on cabal) installed 0.13 , which did parse...

Conclusion: non-issue :smile: 

Thanks for the reply and sorry for needlessly bothering you!

**Comment by HuwCampbell** [comment]
Not a problem
