### ISSUE TITLE
Flags/switches succeed incorrectly when given an argument.

### ISSUE THREAD

**Issue by awpr** [pcapriotti/optparse-applicative#242]
Caused by https://github.com/pcapriotti/optparse-applicative/commit/71ec7f8a1ded84526058a8c61524fb819ada3680.

Now (flag' True (long "aoeu")) succeeds on "--aoeu=7" but then tries to parse "-7" as a separate argument.  This breaks arrangements like (flag' True (name "aoeu") <|> option auto (name "aoeu")) (i.e. accepting "--aoeu", "--aoeu=True", and "--aoeu=False"), which rely on flags failing when given an argument.

Some possible solutions:

- Include in OptWord a Bool indicating whether the word was "--flag=value" or "-fvalue",  and push the value back as an argument only for the latter case.
- Make the unix-style flag combining an optional feature with a Bool in FlagReader to indicate whether it should push its value back as an argument.

**Comment by HuwCampbell** [comment]
So it looks like there are two things going on here.

The first is that you're using overlapping flags and options, which we don't actually support, but used to work in this case.

The reason it's unsupported it because it would have been broken with `--aoeu True` as input, as this style of parsing can be ambiguous.

It might be possible to provide a construct which does this, but explicitly excludes the possibility of providing the option separate from option part, i.e., it must be in the `OptWord`. I'll have to nut that idea around.

Next up is a real bug, in that yes, we shouldn't pop off a flags parse word value if it's specified as a long option.

**Comment by HuwCampbell** [comment]
Please see #247 
I've put the guard back in instead of an error so your trick will still work.
