### ISSUE TITLE
subparser API

### ISSUE THREAD

**Issue by bfrk** [pcapriotti/optparse-applicative#260]
This is more a question than an issue. Why does the subparser/command API use the Monoid interface and not Alternative? That is, why not (example from the readme)

```
  command "add" (info addOptions ( progDesc "Add a file to the repository" ))
  <|>
  command "commit" (info commitOptions ( progDesc "Record changes to the repository" ))
```

My intuition: the user can invoke either the "add" or the "commit" command but not both. Isn't this what Alternative is normally used for?

**Comment by HuwCampbell** [comment]
It was like this before I started helping out as maintainer, but I think there's two reasons, one is mostly historical, in fcd896486ab7a229faa716e775d6f2b1e23c23ee it was set to this to make the continuation in the sub command parser more similar to the option readers.

The other is more to do with API design encouraging good CLI conventions, when a program is using sub commands, all alternatives should essentially take up one "space" on the command line, so the whole is considered a single branch. We know this from things like the cabal and git usage texts, and it is reflected in our usage texts for free:
```
example COMMAND
```
instead of
```
example ( COMMAND | COMMAND | COMMAND )
```
It also makes it easier to write sensible things, where nonconformant CLIs like
```
example ( COMMAND | --blah COMMAND | --foo COMMAND )
```
are discouraged.

**Comment by HuwCampbell** [comment]
I'll close this, but feel free to follow up.
