### ISSUE TITLE
Parsers with maybe fields unexepected behavior

### ISSUE THREAD

**Issue by PierreR** [pcapriotti/optparse-applicative#262]
Asking the question about how to get a [failing parser when both fields of a record are Nothing](https://github.com/Gabriel439/Haskell-Turtle-Library/issues/236), @Gabriel439 cames up with a solution.

Unfortunately it does not seem to work out. Here is a transcript in pure `optparse-applicative`:

```
data Arg = Arg
  { _role  :: Maybe String
  , _group :: Maybe String
  }

parseRole  = strOption (long "role" <> help "role of x")
parseGroup = strOption (long "group" <> help  "group of x")

parseArg = parseBoth <|> parseJustRole <|> parseJustGroup

parseBoth = adapt <$> parseRole <*> parseGroup
  where
    adapt role group = Arg { _role = Just role, _group = Just group }

parseJustRole = adapt <$> parseRole
  where
    adapt role = Arg { _role = Just role, _group = Nothing }

parseJustGroup = adapt <$> parseGroup
  where
    adapt group = Arg { _role = Nothing, _group = Just group }

run (Arg r g) =
  putStrLn (List.intercalate " " (catMaybes [g, r]))

main = execParser infop >>= run
  where
    infop = info (helper <*> parseArg) idm
```

```
λ pi3r/haskell/sandbox → ~/.local/bin/sandbox --role slave
Missing: --group ARG

Usage: sandbox (--role ARG --group ARG | --role ARG | --group ARG)
```
Is there any reason why this does not work ?

Thanks for your help.

**Comment by HuwCampbell** [comment]
Hi.

The pattern here is a `Data.These`, that is, `Arg` can be replaced with `These String String` if you need that invariant.

Yes, there's a reason why it doesn't work. It's because when optparse gets the `--role` option, it sets of searching for a matching parser, it then finds the first matching one inside `parseBoth`, and commits to that branch of the `Alternative`. As the first branch also requires the `--group` option, it's failing when it can't find it and the end.

I have an outstanding mental ticket about making the matching in the `Alternative` instance a bit lazier and searching both sides, then only committing on evaluation. But it will probably make parsing less efficient and may have some strange side effects I haven't thought of.

It's still currently possible to write a parser to do this in optparse however, but it's extremely odd and requires some internal APIs. It's "unsupported" which is why I haven't put this one into the manual.

Anyway, here goes:
```haskell
import Data.These
import Options.Applicative
import Options.Applicative.Types

-- Whatever these are
a :: Parser A
b :: Parser B

ab :: Parser (These A B)
ab = fromM (oneM a >>= \a' -> maybe (This a') (These a') <$> oneM (optional b)) <|> fromM (oneM b >>= \b' -> maybe (That b') (flip These b') <$> oneM (optional a))
```

**Comment by HuwCampbell** [comment]
Actually I don't think it can possible to match on both sides of an alternative, as the number of arguments consumed can change as well. If one had a flag on one side an an option on the other, it could mean two parallel parsers are consuming arguments different arguments... too strange to consider.

So that solution is probably it for now.

**Comment by PierreR** [comment]
Thanks for your detailed answer.

As an extra note, my real use case has 4 maybe fields (a,b,c,d) and 6 valid combination  (a, b, bd, c, cd, d)

**Comment by PierreR** [comment]
To give you a bit of context, I am currently parsing the whole record and pattern match on the IO monad to validate the different cases. It is working flawlessly and I guess that is my best bet for now, I was just curious to know if it was possible to encapsulate all the validation logic in the parser.

I believe a real improvement would be to warm the user about the fact that it won't work somehow.

**Comment by HuwCampbell** [comment]
That's an unfortunate situation for a user interface. Expressing that to a user is difficult enough ( how would you like the help text to appear? ).

The above logic should still work, I would also consider:
1. Figuring out a new interface; or
2. Doing what you're doing, but also building the parser usage and help, but replacing the error message with your own for on unexpected input, so it appear just like a normal parser failure.

I'll close this issue, but feel free to follow up.
