### ISSUE TITLE
Parser that always fail with given ParseError

### ISSUE THREAD

**Issue by hazzus** [pcapriotti/optparse-applicative#380]
Possibly, there is a way to compose such parser, but I didn't get it myself.

Use case: 
I'm using optparse-applicative for creating commands inside my own Haskell-driven shell.
I want to create something like
```sh
/home/hazzus $ stack run
/home/hazzus >>> help
<some help>
# but now I only get this
# because of using  `execParserPure` on the interactive input
/home/hazzus >>> --help
<some help>
```

So code I want to write looks something like:
```haskell
commandParser :: Parser Command
commandParser = hsubparser 
  (command "help" (info failWithHelp) $ 
    progDesc "show this help message")

-- despite having a type Command I want it to 
-- fail with ShowHelpText at the hsubparser level
failWithHelp :: Parser Command 
failWithHelp = ???
```

So my proposal is to add something like
`fail :: ParseError -> Parser a`
Or I wish somebody could help me to handle my problem with existing ways

**Comment by HuwCampbell** [comment]
So this request is a bit tricky for me because I actually think the direction we should go is to ditch being like a free Alternative (having any empty case at all) and move to being like a free [Alt](http://hackage.haskell.org/package/semigroupoids-5.3.4/docs/src/Data.Functor.Alt.html#Alt).

Nonetheless, there's a bit of a hack to make this work if you want to, which is putting an `argument` parser after a `command` parser as an alternative, with a `ReadM` which parses particular error messages.

ghc-mod did this [here](https://github.com/DanielG/ghc-mod/blob/96c2207f0e9019f958d39582d4bf4af3bc9469d2/src/GhcMod/Exe/Options.hs).

**Comment by HuwCampbell** [comment]
I don't think providing pre-failed parsers is a good idea for optparse.

I'm going to close this issue, but feel free to follow up :)
