### ISSUE TITLE
(Question) Is there value in storing CLI output in a text file and using it as a golden test? 

### ISSUE THREAD

**Issue by eyeinsky** [pcapriotti/optparse-applicative#466]
When using `optparse-applicative`, is there any sense in running a program with no arguments and storing it in, say, `golden-cli.txt` and having a test in CI that runs the program and compares if the output still matches the text file?

On one hand, this ensures you'll always know when the CLI changes and don't change it accidentally, but on the other, doesn't this just force developers to change two files instead of one when they *do* want to change the CLI (the two files being the haskell definitions of the CLI *and* the `golden-cli.txt`), as one is generated from the other?

Thanks!

**Comment by HuwCampbell** [comment]
I would say this is purely personal preference.

If you don't have a lot of unit and property tests, then this sort of test can work as a broad integration test for the program, but its granularity would be poor.

If you want to test the parser itself, then adding a "dry-run" flag to the parser, and printing out a json struct or rendering of the expected actions would be the way to go. Otherwise, you'd be testing the whole interactive program, including its internal logic and IO.
