### ISSUE TITLE
bytestring parser

### ISSUE THREAD

**Issue by clinty** [pcapriotti/optparse-applicative#65]
I'd like to parse bytestrings from System.Posix.Env.ByteString.getArgs instead of converting from String.

**Comment by xaverdh** [comment]
Actually I sort of have a use case for this. The issue is that a `cli` program may get passed a raw string (as in `ByteString`), say via a flag, which it then has to pass unmodified to another process.
Currently this does not work with `optparse-applicative`, since the string would have to be converted in a potentially lossy fashion to a `String`.

While it is true that `optparse-applicative` needs to have some encoding to work with, that does not mean, that it has to receive its input in an already decoded form.
A solution might be to to decode parts of the input on the fly with user supplied function, only those parts which need to be decoded – lazy decoding in a sense.

**Comment by xaverdh** [comment]
To to state this a little bit clearer (hopefully):
I envision the user supply a list of `ByteString` values and a function `ByteString -> Maybe String` (which would actually get a sane default). The library (`optparse-applicative`) would then convert the values on the fly as needed. When `Nothing` occurs the input should be considered invalid. Then option parsers could return the raw `ByteString` without having to decode it at all.
This works, because the data is already structured as a list and most of the time we don't actually have to look into the values.
That works for "--opt val" style options, but does not work for "--opt=val" obviously.
That would require extending the user supplied function to a richer type (something like
`ByteString -> [Maybe (String,ByteString)]`, i.e. splitting off the possible prefixes of the decoded input)

**Comment by xaverdh** [comment]
Ok, looking at the actual code, a saner way to do this might be to allow the input to be anything and let the user supply both a decoding function `: InputType -> Maybe String` as well as the `parseWord : InputType -> Maybe OptWord` function, where `data OptWord = OptWord OptName (Maybe InputType)`.
This would allow to implement a `ByteString` variant as described above.

**Comment by hasufell** [comment]
> How would this work, exactly? The arguments would still need to be decoded and converted into a text data type

This is a very common misconception. No, they don't.

> needs to split on spaces, recognise certain special characters, etc, so it can't work on pure ByteString's

This works fine. You can split on spaces and special ascii characters just fine with bytestring. What exactly is the problem? Anything you don't need to parse, you don't parse.

---

For example, filepaths on unix are ByteString (that's what you get back from the syscalls). If you convert them to String, you lose the underlying encoding (and the bytestring representation is potentially different). Now everything further you do with said filepath in your codebase is going to be potentially wrong, including simple things like `==`.

This means in fact I can't trust optparse-applicative to deal with filepaths passed in by a user.

**Comment by luke-clifton** [comment]
So, on unix, filepaths are `ByteString`s, however, that does not mean that Haskell's `String` type can't handle them. GHC uses various `TextEncoding`s when it deals with the outside world. Of particular interest here is [the file system encoding](https://hackage.haskell.org/package/base-4.14.0.0/docs/GHC-IO-Encoding.html#v:getFileSystemEncoding). which, on non-windows systems, is used for argument reading as well (see `argvEncoding` in the same file).

By default, the file system encoding uses "UTF-8b", which actually embeds invalid utf-8 sequences using "surrogate escaping". As long as you use the same encoding when converting back to bytes, it is actually perfectly possible to round trip arbitrary data through a Haskell `String`. It should go without saying that `System.IO.openFile` and friends all do the right thing here. So, if your plan is to just open a file, using the standard Haskell interfaces, everything should just work.

On the other hand, if you want to pass it to a function expecting a `ByteString` (especially all the ones in `System.Posix.ByteString`), then you need to convert it to a `ByteString` correctly.

Now, there is no official way to actually convert such a `String` to a `ByteString` as far as I am aware. Your best bet is probably:

```
import GHC.Foreign
import GHC.IO.Encoding
import qualified Data.ByteString as B

filepathToByteString :: FilePath -> IO B.ByteString
filepathToByteString path = do
    encoding <- argvEncoding
    GHC.Foreign.withCStringLen encoding path B.packCStringLen
```

Which will reverse the process correctly.

More about encodings not really related to option parsing:

Reading `FilePaths` from stdin using `getLine` will not work because the the the file system encoding is not used for this handle, instead the locale encoding is used. You can change the encoding being used with `hSetEncoding stdin`. If you set it to the file system encoding, then you can use `getLine` to read filepaths from stdin using the same encoding as is used for arguments, and passing it to `openFile` will Just Work. (ignore files with newlines for now, this all applies to using `\0` delimited names as well, but `getLine` is easy for demo purposes)

As a side note: if you see the [`FilePath`](https://hackage.haskell.org/package/base-4.15.0.0/docs/System-IO.html#t:FilePath) type alias, you should be assuming that this is encoded using the file system encoding, which on unix can handle arbitrary data. The documentation for `FilePath` even says

> File and directory names are values of type String, whose precise meaning is operating system dependent.

Which is suggesting that there is something strange going on with the encoding. The fact that `FilePath` is not a distinct type from `String` causes a lot of grief here.

**Comment by HuwCampbell** [comment]
Interesting. I'm open to opening a branch on top of these proposals.

I'm pretty conservative with changes here because optparse is a 10 yo project people just use and expect to work. But if base is moving, yeah, we can and should too.

**Comment by hasufell** [comment]
@pcapriotti can you please re-open this ticket?

**Comment by hasufell** [comment]
Demonstration of unsoundness of current roundtripping techniques: https://gist.github.com/hasufell/c600d318bdbe010a7841cc351c835f92

HF tech proposal outlining the current affairs: https://github.com/haskellfoundation/tech-proposals/issues/35

**Comment by Merivuokko** [comment]
Hello,

I am writing Unix utilities in Haskell, and I need support for OsPath and OsString from the new filepath library.

I understand that optparse-applicative has been built on type String = [Char] and it would require major changes to be able to support plain octet streams instead of encoded text as input.

Therefore I'm kindly asking, are there any plans for optparse-applicative to transition to using OsStrings (or ByteStrings) in foreseeable future (while I could use some ad hoc CLI parser in the meanwhile), or should I consider planning a new CLI parsing library?

**Comment by hasufell** [comment]
@Merivuokko first, we need to implement the following function properly and multiplatform:

```hs
getArgs :: [OsString]
```

This is currently blocked because I can't see that [`GetCommandLineW`](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinew) function is implemented/exposed in [Win32 package](https://hackage.haskell.org/package/Win32). So you'd need to create a wrapper yourself.

For unix, it's fairly trivial:

```hs
module Main where

import Data.ByteString.Short (ShortByteString)         -- bytestring
import System.OsString.Internal.Types                  -- filepath
import qualified System.Posix.Env.PosixString as Posix -- unix

main :: IO ()
main = do
  args <- getArgs
  print args

getArgs :: IO [OsString]
getArgs = fmap OsString <$> Posix.getArgs
```

**Comment by hasufell** [comment]
https://github.com/haskell/win32/pull/221

**Comment by Merivuokko** [comment]
> https://github.com/haskell/win32/pull/221

Thank you very much! I was about to create an issue on Win32, as this is the
best that I could have done. I don't know much about that platform and have
only tried it once (some 25 years ago).

**Comment by hasufell** [comment]
My current efforts are here: https://github.com/hasufell/optparse-applicative/pull/1/files

**Comment by hasufell** [comment]
There are two more steps needed:

* augment filepath package to have proper bytestring like functions (splitAt etc.): https://github.com/haskell/filepath/pull/202
* provide a megaparsec or attoparsec variant for `OsString`
